version: '3.8'

services:
  db:
    image: 'postgres:12.2'
    env_file:
      - '.env-prod'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis'
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file:
      - '.env-prod'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  
  jobs:
    build: .
    command: bash start_jobs.sh
    env_file:
      - '.env-prod'
    volumes:
      - '.:/oneohonesecretfriend'
    volumes_from:
      - box
    depends_on:
      - db
      - redis
      - app

  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    env_file:
      - '.env-prod'
    volumes:
      - .:/oneohonesecretfriend
    volumes_from:
      - box
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  redis:
  gems:
  box:
