version: '3.8'

services:
  db:
    image: 'postgres:12.2'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis'
    command: redis-server --requirepass REDIS#2020!
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/nosso_amigo_secreto'
    volumes_from:
      - box
    depends_on:
      - db
      - redis
      - app

  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/oneohonesecretfriend
    volumes_from:
      - box
    depends_on:
      - db
      - redis

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  redis:
  gems:
  box:
